OBJ = allocate_memory.c balance.c inorder.c insert.c left_rotate.c main.c postorder.c preorder.c right_rotate.c sibling.c user_input.c value_in_node.c
rb_tree : $(OBJ)
	gcc -o $@ $^ -include rb_tree.h -g
