.TH "src/main.c" 3 "Thu Jul 19 2018" "Version 2" "dining philosopher problem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBphil\fP [SIZE] = {0, 1, 2, 3, 4, 5}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
@ phil is an array of SIZE index is integer variable 
.SH "Variable Documentation"
.PP 
.SS "int phil[SIZE] = {0, 1, 2, 3, 4, 5}"

.SH "Author"
.PP 
Generated automatically by Doxygen for dining philosopher problem from the source code\&.
